package generator

import (
	"fmt"
	"strings"

	"protoc-gen-struct/generator/language"

	"google.golang.org/protobuf/types/descriptorpb"
)

// generatedHeader is the notice every generated file opens with, marking the file as machine
// written so it is not edited by hand and is recognizable to tooling that skips generated code.
// the wording is not free: Go's tooling matches "^// Code generated .* DO NOT EDIT\.$" exactly, so
// gopls and the linters only skip a generated file that carries the prefix and the trailing period
const generatedHeader = "Code generated by github.com/David0922/protoc-gen-struct. DO NOT EDIT."

// Generate generates code for a single proto file in the specified language. determines output filename from input proto filename and target language
//
// file: the FileDescriptorProto to generate code for
// allFiles: all proto files for type resolution, including every transitive import
// filesToGenerate: names of the files protoc asked for, which is what has generated output
// lang: target language (go, c++, python, typescript)
//
// content: the generated code
// filename: output filename
// err: generation errors
func Generate(file *descriptorpb.FileDescriptorProto, allFiles []*descriptorpb.FileDescriptorProto, filesToGenerate []string, lang string) (string, string, error) {
	// validate the descriptor before handing it to a generator: the generators dereference the
	// file name, so this check has to happen first
	if file.Name == nil {
		return "", "", fmt.Errorf("file descriptor has no name")
	}

	// create type registry for reference resolution
	registry := language.NewTypeRegistry(allFiles, filesToGenerate)

	var gen language.Generator
	var ext string
	// the marker each language opens a line comment with. every target here has one, so the
	// header never has to be written as a block comment
	var comment string

	switch strings.ToLower(lang) {
	case "c++", "cpp":
		gen = language.NewCppGenerator(registry)
		ext = ".h"
		comment = "//"
	case "go":
		gen = language.NewGoGenerator(registry)
		ext = ".go"
		comment = "//"
	case "python":
		gen = language.NewPythonGenerator(registry)
		ext = ".py"
		comment = "#"
	case "ts", "typescript":
		gen = language.NewTypescriptGenerator(registry)
		ext = ".ts"
		comment = "//"
	default:
		return "", "", fmt.Errorf("unsupported language: %s", lang)
	}

	// generate code
	content, err := gen.Generate(file)
	if err != nil {
		return "", "", err
	}

	// prepend the generated-file notice. the blank line after it matters for Go, where a comment
	// sitting directly above the package clause would be read as the package doc comment instead
	content = fmt.Sprintf("%s %s\n\n%s", comment, generatedHeader, content)

	// determine output filename. the source directory is kept rather than flattened: two protos of
	// the same name in different directories would otherwise be written to one path, which protoc
	// rejects outright, and the generated file has to sit where its package layout expects it
	outputFile := language.ProtoFileStem(*file.Name) + ext

	return content, outputFile, nil
}
